- name: Exécuter le script PowerShell pour chaque utilisateur
  hosts: win
  tasks:
    - name: Obtenir la liste des utilisateurs connectés
      win_shell: quser | Where-Object { $_ -notmatch $env:USERNAME } | Select-Object -Skip 1
      register: quser_output

    - name: Afficher la liste des utilisateurs
      debug:
        var: quser_output.stdout_lines[1:]

    - name: Exécuter le script PowerShell pour chaque utilisateur
      win_shell: |
        $os_family = ansible_os_family

        if ($os_family -eq "Windows") {
          Add-Type -AssemblyName Microsoft.VisualBasic
          Add-Type -AssemblyName System.Windows.Forms

          $result = [Microsoft.VisualBasic.Interaction]::MsgBox('Une mise à jour NSDK a été lancée, vous serez déconnecté dans 5 minutes!! Appuyez sur Yes pour être déconnecté maintenant', 'YesNo', 'Mise à jour NSDK')

          if ($result -eq 'Yes') {
              $sessionId = (quser | Select-String "Active" | ForEach-Object { ($_ -split "\s+")[2] }).Trim()

              $wts = Add-Type -MemberDefinition @"
              [DllImport("wtsapi32.dll")]
              public static extern bool WTSDisconnectSession(IntPtr hServer, int sessionId, bool bWait);
"@
              $wts::WTSDisconnectSession([IntPtr]::Zero, $sessionId, $true)
          }
          else {
              [System.Windows.Forms.MessageBox]::Show('Déconnexion dans 5 min', 'Mise à jour NSDK')
          }
        }
      register: script_output

    - name: Afficher la sortie du script pour chaque utilisateur
      debug:
        msg: "{{ script_output.stdout }}"
