---
- name: Copier un dossier depuis le nœud de contrôle vers une machine Windows
  hosts: win
  tasks:
    - name: Copier le dossier depuis le nœud de contrôle vers la machine Windows
      win_copy:
        src: /home/ansible/Version_1.zip
        dest: C:\Users\ansible\Desktop\Version_1.zip

    - name: Extraire le fichier ZIP
      community.windows.win_unzip:
        src: C:\Users\ansible\Desktop\Version1.zip
        dest: C:\Users\ansible\Desktop\
        delete_archive: yes
