---
- name: Trouver l'ID du processus RevoUn.exe dans le chemin spécifié
  hosts: win
  tasks:

    - name: Trouver l'ID du processus RevoUn
      win_shell: Get-Process RevoUn | Where-Object {$_.Path -like "C:\Users\ansible\Desktop\Version_1*"} | Select-Object -ExpandProperty Id
      register: process_id_result

    - name: Afficher le résultat
      debug:
        var: process_id_result


    - name: Arrêter le processus RevoUn.exe
      win_shell: Stop-Process -Id "{{ process_id_result.stdout }}" -Force
      when: process_id_result.stdout is defined

    - name: Supprimer les fichiers dans le chemin d'exécution
      win_shell: Remove-Item -Path "C:\Users\ansible\Desktop\Version_1\*" -Recurse -Force

    - name: Extraire le fichier ZIP
      community.windows.win_unzip:
        src: C:\Users\ansible\Desktop\Version_1.zip
        dest: C:\Users\ansible\Desktop\
        delete_archive: no

    - name: Exécuter RevoUn.exe dans le dossier Version_1
      win_shell: "C:\Users\ansible\Desktop\Version_1\RevoUn.exe"
