---
- name: Get RevoUn.exe processes
  hosts: windows_servers
  tasks:
    - name: Get RevoUn.exe processes
      ansible.windows.win_command: Get-Process | Where-Object {$_.ProcessName -eq "RevoUn"} | Select-Object Id, ProcessName, Path
      register: revo_processes
    
    - name: Display RevoUn.exe processes
      debug:
        msg: "{{ revo_processes.stdout_lines }}"
