---
- name: Check Pid
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Get Name, Id, Path of "RevoUn" process
      win_shell: 'Get-Process | Where-Object {$_.ProcessName -like "RevoUn"} | Select-Object Name, Id, Path'
      register: ps_version_output

    - name: Display results
      debug:
        var: ps_version_output.stdout_lines

    - name: Write result to a file
      copy:
        content: "{{ ps_version_output.stdout_lines | join('\n') }}"
        dest: "C:\\Users\\ansible\\Desktop\\output.txt"

- name: Read output.txt and display PID of process with specific path
  hosts: localhost  # Assuming you want to run this task on the Ansible control node
  gather_facts: no
  tasks:
    - name: Read output.txt
      slurp:
        src: "C:\\Users\\ansible\\Desktop\\output.txt"
      register: output_file

    - name: Extract content from output.txt
      set_fact:
        file_content: "{{ output_file['content'] | b64decode }}"

    - name: Get PID of process with specific path
      win_shell: 'Get-Content "{{ file_content }}" | Where-Object { $_ -match "C:\\Users\\ansible\\Desktop\\Version_2\\RevoUn.exe" } | ForEach-Object { $_.Split()[1] }'
      register: pid_output

    - name: Display PID
      debug:
        var: pid_output.stdout
